(() => {
    const english = {
        10001: ["What is the difference between a physical change and a chemical change?", "A physical change involves no chemical reaction and forms no new substance. A chemical change involves a chemical reaction and forms one or more new substances."],
        10002: ["Define an element.", "A pure chemical substance consisting of only one type of atom."],
        10003: ["Give two examples of metalloids.", "Boron and silicon."],
        10004: ["State one use of silicon.", "Making computer chips or integrated circuits."],
        10005: ["State the meanings of malleability and ductility.", "Malleability is the ability of a metal to be hammered into different shapes. Ductility is the ability of a metal to be drawn into wires."],
        10006: ["Name the subatomic particles in an atom and state their relative charges and relative masses.", "Proton: relative charge = +1, relative mass = 1. Neutron: relative charge = 0, relative mass = 1. Electron: relative charge = −1, relative mass ≈ 0."],
        10007: ["Which subatomic particles are inside the nucleus, and which are outside it?", "Protons and neutrons are inside the nucleus, while electrons are outside the nucleus."],
        10008: ["Explain why an atom is electrically neutral.", "An atom contains equal numbers of positively charged protons and negatively charged electrons."],
        10009: ["Do all atoms contain protons, neutrons and electrons? Explain.", "No. A hydrogen atom has no neutron."],
        10010: ["State the meanings of atomic number and mass number.", "Atomic number = the number of protons in an atom. Mass number = the total number of protons and neutrons in an atom."],
        10011: ["Define isotopes.", "Isotopes are atoms of the same element with the same number of protons but different numbers of neutrons."],
        10012: ["State and explain the relationship between 12C and 13C.", "They are isotopes because they have the same number of protons but different numbers of neutrons."],
        10013: ["A student says that carbon has three isotopes, and because Si is in the same group as carbon, Si must also have three isotopes. Comment on this statement.", "The statement is incorrect because the number of isotopes is unrelated to an element's position in the periodic table."],
        10014: ["State whether isotopes have the same chemical properties, and explain your answer.", "Yes. Isotopes have the same number of electrons."],
        10015: ["State whether isotopes have the same physical properties, and explain your answer.", "No. Isotopes have different numbers of neutrons."],
        10016: ["State the meaning of relative isotopic mass.", "The relative mass of an isotope on the scale where 12C = 12.00."],
        10017: ["State the relative isotopic masses of 12C and 13C.", "12C = 12; 13C = 13."],
        10018: ["State the meaning of relative atomic mass.", "The weighted average of the relative isotopic masses of all the isotopes of an element on the scale where 12C = 12.00."],
        10019: ["Can the isotopes of magnesium be separated by chemical methods? Explain your answer.", "No. Magnesium isotopes have the same chemical properties."],
        10020: ["10BCl3 and 11BCl3 are given. 10BCl3 produces white fumes when it reacts with water. State the expected observation when 11BCl3 is added to water and explain it.", "White fumes are produced because 10B and 11B are isotopes and have the same chemical properties."],
        10021: ["What formula gives the maximum number of electrons that an electron shell can hold? Hence find the maximum number for the third shell.", "2n2; 2(3)2 = 18."],
        10022: ["X and Y are elements with electron arrangements 2,8,8 and 2,8,18,y respectively. The atomic number of Y is 36. Find y.", "8."],
        10023: ["When 24Mg reacts with steam, a colourless gas is produced. State what happens when 26Mg reacts with steam and explain.", "A colourless gas is also produced. 24Mg and 26Mg are isotopes with the same number of electrons, so they have the same chemical properties."],
        10024: ["Find the proton number, mass number and number of neutrons of this atom.", "Proton number = 11; mass number = 23; number of neutrons = 23 − 11 = 12."],
        10025: ["Draw the electron diagram of a sodium atom.", "The electron arrangement of sodium is 2,8,1 (see diagram)."],
        10026: ["Use its electron arrangement to explain why helium is stable.", "Helium has two outermost-shell electrons, giving it a stable duplet electron arrangement."],
        10027: ["Explain why argon is stable.", "Argon has eight outermost-shell electrons, giving it a stable octet electron arrangement."],
        10028: ["Explain why a magnesium atom is unstable.", "A magnesium atom has two outermost-shell electrons and does not have a stable octet electron arrangement."],
        10029: ["State how elements are arranged in the periodic table.", "By atomic number."],
        10030: ["State the meanings of group number and period number.", "Group number = the number of outermost-shell electrons in an atom. Period number = the number of occupied electron shells in an atom."],
        10031: ["Do elements in the same group always have the same number of outermost-shell electrons? If not, explain.", "No. Helium in Group 0 has two outermost-shell electrons, while the other Group 0 elements have eight."],
        10032: ["Give the names of Groups I, II, VII and 0.", "Group I: alkali metals. Group II: alkaline earth metals. Group VII: halogens. Group 0: noble gases."],
        10033: ["How can atoms obtain stable electron arrangements?", "By losing electrons, gaining electrons or sharing electrons."],
        10034: ["Draw the electron diagrams of Cl2, N2H4 and CO2.", "Use the number of outermost-shell electrons of each atom and ensure that every atom attains a stable electron arrangement."],
        10035: ["State and explain what is special about the chemical properties of elements in the same group.", "Their chemical properties are similar because they have the same number of outermost-shell electrons. Remember: similar, not identical."],
        10036: ["State and explain how atomic size changes down a group.", "Atomic size increases because the number of occupied electron shells increases down a group."],
        10037: ["State how the melting points and boiling points of Groups I, II and III change down the group.", "The melting points and boiling points decrease down the group."],
        10038: ["State how the reactivity of Groups I, II and III changes down the group.", "Reactivity increases down the group."],
        10039: ["State three trends across a period in the periodic table.", "The elements change from metals to metalloids to non-metals; atomic size decreases; and the tendency to lose electrons decreases because metals lose electrons while non-metals gain electrons."],
        10040: ["Why must Group I metals be stored under paraffin oil?", "Group I metals are very reactive. The oil prevents contact with air and the formation of an oxide layer."],
        10041: ["A freshly cut piece of lithium is left in air. What change is observed on its surface after some time? Write the relevant word equation.", "The surface becomes dull. Lithium + oxygen → lithium oxide."],
        10042: ["Why can lithium metal be cut easily?", "Group I metals are soft."],
        10043: ["Why should Group I metals not be reacted with acids?", "The reactions between Group I metals and acids are explosive."],
        10044: ["State one hazard warning label that should be displayed for Group I metals.", "Corrosive."],
        10045: ["Why should Group I metals not be touched by hand?", "Group I metals are corrosive."],
        10046: ["How should Group I metals be handled in the laboratory?", "Use forceps."],
        10047: ["State two observations when lithium reacts with water.", "It floats on the water, dissolves, and produces colourless gas bubbles."],
        10048: ["State two observations when sodium reacts with water.", "It moves rapidly on the water, melts into a silvery ball, burns with a golden-yellow flame, and produces colourless gas bubbles."],
        10049: ["State two observations when potassium reacts with water.", "It moves rapidly on the water, melts into a silvery ball, burns with a lilac flame, and produces colourless gas bubbles."],
        10050: ["Potassium and sodium both move rapidly on water. Which metal moves faster? Explain your answer.", "Potassium, because the reactivity of Group I metals increases down the group."],
        10051: ["Which substances exist as diatomic molecules?", "Nitrogen, oxygen, hydrogen and the Group VII elements."],
        10052: ["Explain why oxygen exists as diatomic molecules.", "An oxygen atom has only six outermost-shell electrons, so it is not stable as a single atom."],
        10053: ["Explain why argon can exist as single atoms.", "Argon has eight outermost-shell electrons and a stable octet electron arrangement."],
        10054: ["State how the melting points and boiling points of Group VII elements change down the group.", "The melting points and boiling points increase down the group."],
        10055: ["State how the reactivity of Group VII elements changes down the group.", "Reactivity decreases down the group."],
        10056: ["Do all metals have densities greater than water? If not, name the metals with densities lower than water.", "No. The Group I metals lithium, sodium and potassium have densities lower than water."],
        10057: ["Why do Group II metals undergo very similar reactions?", "All Group II metals have two outermost-shell electrons."],
        10058: ["How can an ionic compound be identified, and what does an ionic compound consist of?", "Metal + non-metal, or NH4+ + non-metal. An ionic compound consists of cations and anions."],
        10059: ["How can a covalent compound be identified, and what does it consist of?", "Two different non-metals share electrons. A covalent compound consists of atoms."],
        10060: ["How can an element be identified, and what does an element consist of?", "It contains only one element. An element consists of atoms."],
        10061: ["Classify each substance as an element, ionic compound or covalent compound: Cl2, NaCl, NH4Cl and CO2.", "Element = Cl2. Ionic compounds = NaCl and NH4Cl. Covalent compound = CO2."],
        10062: ["What can you deduce from the graph?", "The reactivity of Group II metals increases down the group."],
        10063: ["Why must Group VII elements be handled in a fume cupboard in the laboratory?", "Group VII elements are toxic and have unpleasant odours."],
        10064: ["Chlorine and fluorine are gases at room temperature and pressure. Explain why they should not be identified by smelling them directly.", "Both gases are toxic."],
        10065: ["When should an experiment be carried out in a fume cupboard?", "When the experiment involves toxic or carcinogenic substances."],
        10066: ["State the trend in the melting points of Group VII elements down the group.", "They increase down the group."],
        10067: ["State the trend in the reactivity of Group VII elements down the group.", "It decreases down the group."],
        10068: ["Why do Group 0 elements rarely react, or why are they chemically inert?", "They have stable octet or duplet electron arrangements."],
        10069: ["State one use of helium and explain why it is suitable.", "It is used to fill balloons and airships because it has a low density and is non-flammable."],
        10070: ["Why is hydrogen not used to fill balloons?", "Hydrogen is flammable and explosive."],
        10071: ["Write the chemical equation for the explosive reaction of hydrogen.", "H2 + O2 → H2O."],
        10072: ["State one use of neon and explain why it is suitable.", "It is used to fill neon tubes because it emits red light when electricity passes through it."],
        10073: ["State one use of argon and explain why it is suitable.", "It is used to fill light bulbs because argon does not react with the tungsten filament."],
        10074: ["What is the problem with filling a light bulb with air?", "At high temperatures, the tungsten filament reacts with oxygen in the air."],
        10075: ["Xe is a Group 0 element. A balloon filled with Xe is released from the top of a tower. State and explain the observation. Relative atomic masses: N = 14.0, O = 16, Xe = 131.3.", "The balloon falls because Xe is denser than air."],
        10076: ["A balloon filled with hydrogen is released from the top of a tower. State and explain the observation. Relative atomic masses: H = 1, N = 14, O = 16.", "The balloon rises because hydrogen is less dense than air."],
        10077: ["What is observed when an iron nail is placed in water?", "The iron nail sinks to the bottom."],
        10078: ["State one similarity in the atomic structures of Group VII elements.", "They all have seven outermost-shell electrons."],
        10079: ["Why does NaCl(s) not conduct electricity?", "The ions in NaCl(s) cannot move freely, so there are no mobile ions to conduct electricity."],
        10080: ["Why can Mg(NO3)2(aq) conduct electricity?", "It contains mobile ions that conduct electricity."],
        10081: ["Why can MgCl2(l) conduct electricity?", "It contains mobile ions that conduct electricity."],
        10082: ["Why can Mg conduct electricity?", "It contains delocalised electrons that conduct electricity."],
        10083: ["Explain why nitrogen is difficult to decompose even at extremely high temperatures, or why nitrogen is generally unreactive.", "A nitrogen molecule contains a covalent triple bond and is therefore very stable."],
        10084: ["Using the melting-point and conductivity data for XCl, YCl3 and ZCl5, explain why XCl does not conduct at 700°C but conducts at 850°C.", "At 700°C, XCl is solid and has no mobile ions. At 850°C, the temperature is above its melting point, so XCl is liquid and has mobile ions that conduct electricity."],
        10085: ["What colour appears in the middle of the filter paper after the circuit is closed? Explain.", "Green, because green Fe2+(aq) ions are attracted to the negative electrode and move towards the centre."],
        10086: ["Why is the filter paper soaked with Na2SO4(aq)? What happens if pure water is used instead? Explain.", "Na2SO4(aq) improves conductivity because it contains mobile ions. With pure water, no observable change occurs because pure water does not conduct electricity."],
        10087: ["What happens if the positive and negative electrodes in the setup are reversed? Explain your answer.", "No observable change appears in the middle of the filter paper. The colourless SO42-(aq) ions move towards the positive electrode, while the colourless K+(aq) ions move towards the negative electrode."],
        10088: ["Outline an experiment showing that copper(II) dichromate consists of ions, and state the observations. Cu2+(aq) is blue and Cr2O72-(aq) is orange.", "Soak filter paper with sodium sulphate solution and connect it to a d.c. power supply. Add copper(II) dichromate solution at the centre. The orange spot moves towards the positive electrode and the blue spot moves towards the negative electrode, showing the presence of mobile ions."],
        10089: ["Define an ionic bond.", "An ionic bond is the strong electrostatic attraction between cations and anions."],
        10090: ["Using NaCl as an example, state all the bonds and forces present.", "NaCl contains strong ionic bonds between Na+ and Cl- ions."],
        10091: ["Describe how the ionic bond in NaCl is formed.", "Each Na atom loses one outermost-shell electron to form Na+. Each Cl atom gains an electron from Na to form Cl-. An ionic bond forms between Na+ and Cl-."],
        10092: ["Describe how the ionic bonds in MgF2 are formed.", "Each Mg atom loses two outermost-shell electrons to form Mg2+. Each F atom gains one electron from Mg to form F-. Ionic bonds form between Mg2+ and F-."],
        10093: ["When Se reacts with Al, each Se atom gains two electrons to form a Se ion and compound X is produced. Name the type of bonding in X.", "Ionic bonding."],
        10094: ["Write the chemical formula of X and draw its electron diagram.", "Al2Se3."],
        10095: ["Is ionic bonding directional?", "No."],
        10096: ["Define a metallic bond.", "A metallic bond is the strong electrostatic attraction between metal ions and delocalised electrons."],
        10097: ["Using Mg as an example, state the bonding present.", "Mg contains strong metallic bonds between Mg2+ ions and delocalised electrons."],
        10098: ["Draw the three-dimensional structure of Mg.", "A giant metallic structure consists of regularly arranged Mg2+ ions surrounded by delocalised electrons (see diagram)."],
        10099: ["Is metallic bonding directional?", "No."],
        10100: ["Define a covalent bond.", "A covalent bond is the strong electrostatic attraction between a shared pair of electrons and the bonded atoms."],
        10101: ["Is covalent bonding directional?", "Yes."],
        10102: ["State four examples involving coordinate covalent bonds in the DSE syllabus.", "NH4+, H3O+, NH3BF3 and CO."],
        10103: ["Define a coordinate covalent bond.", "A coordinate covalent bond is a covalent bond in which the shared pair of bonding electrons is supplied by only one of the two bonded atoms."],
        10104: ["Using NH4+ (formed from NH3 + H+) as an example, describe the formation of a coordinate covalent bond.", "H+ has no electrons and is electron-deficient. The N atom in NH3 has a lone pair. The N atom forms a coordinate covalent bond with H+, with both bonding electrons supplied by N."],
        10105: ["Using NH4+ as an example, write an equation showing the formation of a coordinate covalent bond.", "NH3 + H+ → NH4+; the nitrogen atom supplies a lone pair to form the coordinate covalent bond."],
        10106: ["Using H3O+ (formed from H2O + H+) as an example, describe the formation of a coordinate covalent bond.", "H+ has no electrons and is electron-deficient. The O atom in H2O has two lone pairs. The O atom forms a coordinate covalent bond with H+, with both bonding electrons supplied by O."],
        10107: ["Using H3O+ (formed from H2O + H+) as an example, write an equation showing the formation of a coordinate covalent bond.", "H2O + H+ → H3O+; the oxygen atom supplies a lone pair to form the coordinate covalent bond."],
        10108: ["Among the H–B, B–N and N–H bonds, which is a coordinate covalent bond? Explain your answer.", "The B–N bond. The B atom in BH3 has only six outermost-shell electrons and is electron-deficient, while the N atom in NH3 has a lone pair. N supplies both bonding electrons to form a coordinate covalent bond with B."],
        10109: ["Why does filling a packet with nitrogen help prevent potato chips from going bad?", "Nitrogen has a covalent triple bond and is very stable, so it does not react with the chips and cause them to spoil."],
        10110: ["Why would filling the packet with air cause the potato chips to go bad?", "Oxygen in the air reacts with the chips and causes them to spoil."],
        10111: ["Helium is also unreactive. Why is it not used to prevent potato chips from going bad?", "Helium is less dense than air, so it may make the packet float."],
        10112: ["Another way to prevent potato chips from going bad is to remove all the air from the packet. State one disadvantage of this method.", "The potato chips are easily crushed."],
        10113: ["Explain why magnesium is malleable and ductile.", "Metallic bonds are non-directional. When a force is applied, magnesium ions slide past one another but remain bonded to the delocalised electrons, so the metal does not break."],
        10114: ["Explain why NaCl is brittle.", "Na+ and Cl- ions in NaCl are held by strong ionic bonds. When a force is applied, the relative movement of ions brings ions with the same charge next to one another, causing repulsion."],
        10115: ["Apart from explaining malleability, ductility and brittleness, other physical properties such as density, hardness, melting point and boiling point are answered in two steps. Explain why NaCl is hard.", "NaCl has a giant ionic structure with strong ionic bonds between Na+ and Cl- ions."],
        10116: ["Explain why Mg has a high density.", "Mg has a giant metallic structure with strong metallic bonds between Mg2+ ions and delocalised electrons."],
        10117: ["Which substances in the DSE syllabus have giant covalent structures?", "Graphite, diamond, SiO2 (silicon dioxide or quartz), B and Si."],
        10118: ["Explain whether diamond or CO2 has the higher boiling point.", "Diamond has a giant covalent structure with strong covalent bonds between carbon atoms. CO2 has a simple molecular structure with weak van der Waals forces between CO2 molecules. Therefore, diamond has the higher boiling point."],
        10119: ["Explain why Mg is solid at room temperature while SO2 is a gas.", "Mg has a giant metallic structure with strong metallic bonds between Mg2+ ions and delocalised electrons. SO2 has a simple molecular structure with weak van der Waals forces between SO2 molecules. Therefore, Mg has a high melting point, while SO2 has a low boiling point."],
        10120: ["The electron arrangement of Kr is 2,8,18,x. What is x?", "8."],
        10121: ["Draw the three-dimensional structure of diamond. One mark is awarded for the diagram and one for the labels.", "Diamond has a giant covalent structure. Each carbon atom is joined to four other carbon atoms by four covalent bonds (see diagram)."],
        10122: ["Define allotropes and give one example.", "Allotropes are different structural forms of the same element. For example, diamond and graphite are allotropes of carbon."],
        10123: ["Draw the structures of graphite and graphene.", "Graphite consists of multiple layers of hexagonal carbon networks. Strong covalent bonds act within each layer, while only weak van der Waals forces act between layers. Graphene is one single layer (see diagram)."],
        10124: ["Explain why graphite conducts electricity. Give the simple one-mark answer.", "Graphite contains delocalised electrons that conduct electricity."],
        10125: ["Explain why graphite conducts electricity. Give the detailed two-to-three-mark answer.", "In graphene, each carbon atom is covalently bonded to three other carbon atoms. The remaining outermost-shell electron from each carbon atom becomes delocalised, so graphite conducts electricity."],
        10126: ["State two everyday uses of graphite.", "Pencil leads and lubricants."],
        10127: ["Explain why graphite can be used to make pencil leads.", "Only weak van der Waals forces act between the graphene layers, so the layers can be removed easily."],
        10128: ["Explain why graphite can be used as a lubricant.", "Only weak van der Waals forces act between the graphene layers, so graphite is soft."],
        10129: ["Explain why graphite is soft.", "Only weak van der Waals forces act between the graphene layers."],
        10130: ["Are substances with giant covalent structures soluble in water or non-aqueous solvents?", "They are insoluble in both water and non-aqueous solvents."],
        10131: ["What is a molecule?", "Particles of substances with simple molecular structures are called molecules."],
        10132: ["List all the bonds and forces present in O2.", "Weak van der Waals forces act between O2 molecules. Within each O2 molecule, a strong covalent bond acts between the two O atoms."],
        10133: ["State all the bonds and forces present in NH4Cl.", "A strong ionic bond acts between NH4+ and Cl-. Within NH4+, strong covalent bonds act between N and H atoms, and a strong coordinate covalent bond acts between N and H+."],
        10134: ["In NaCl, how many Cl- ions surround each Na+ ion?", "6."],
        10135: ["In NaCl, how many Na+ ions surround each Cl- ion?", "6."],
        10136: ["In CsCl, how many Cl- ions surround each Cs+ ion?", "8."],
        10137: ["In CsCl, how many Cs+ ions surround each Cl- ion?", "8."],
        10138: ["Why are school laboratories usually equipped with carbon dioxide fire extinguishers rather than water extinguishers?", "Carbon dioxide does not react with most chemicals, whereas water reacts with many chemicals, such as sodium."],
        10139: ["State how a carbon dioxide fire extinguisher puts out a fire.", "Carbon dioxide is denser than air, so it displaces air and prevents the fire from contacting oxygen, extinguishing the fire."],
        10140: ["A student suggests using helium as a fire-extinguishing agent. Would such an extinguisher be effective? Explain.", "No. Helium is less dense than air and cannot displace the air to stop oxygen from reaching the fire."],
        10141: ["A student suggests using hydrogen as a fire-extinguishing agent. Would such an extinguisher be effective? Explain.", "No. Hydrogen is flammable and explosive, so using this extinguisher could cause an explosion."],
        10142: ["State one use of diamond.", "Making jewellery or cutting tools."],
        10143: ["State one industrial use of silicon dioxide.", "Making glass."],
        10144: ["State one natural source of silicon dioxide.", "Sand."],
        10145: ["Is silicon dioxide an ionic compound or a covalent compound? Explain.", "It is a covalent compound because it consists of a non-metal and a metalloid."],
        10146: ["Compared with platinum, state one advantage of using graphite to make electrodes.", "Graphite is much cheaper than platinum."],
        10147: ["Compared with platinum, state one disadvantage of using graphite to make electrodes.", "Graphite is brittle, while platinum is harder."],
        10148: ["Using the data provided, deduce the types of structure of XCl, YCl3 and ZCl5.", "YCl3 and ZCl5 should have simple molecular structures because they have low melting points and do not conduct electricity. XCl should have a giant ionic structure because it has a high melting point, does not conduct as a solid, but conducts as a liquid."],
        10149: ["Solid X is known not to be graphite. Describe how the structure of X can be determined.", "Test the electrical conductivity of X in the solid and molten states. Conductivity in the solid state indicates a giant metallic structure. No conductivity when solid but conductivity when molten indicates a giant ionic structure. If it does not conduct in either state, measure its melting point: a low melting point indicates a simple molecular structure, while a very high melting point indicates a giant covalent structure."],
        10150: ["A magnesium ribbon changes shape when a force is applied, but iodine shatters. Explain this observation with reference to their structures.", "Metallic bonds are non-directional. When a force is applied, magnesium ions slide past one another but remain bonded to the delocalised electrons, so magnesium does not break. Iodine has a simple molecular structure with weak van der Waals forces between iodine molecules. These forces break when a force is applied, causing iodine to shatter."],
        10151: ["Ge is a Group IV element. Deduce its structure from the following data: melting point 1000°C; boiling point 2000°C; not malleable.", "Because Ge is not malleable, it is not a metal and does not have a giant metallic structure. Its high melting point and boiling point indicate that it has a giant covalent structure."],
        10152: ["A cation has 22 electrons and a mass number of 55. If its charge is +3, how many neutrons does it contain?", "30."],
        10153: ["Element X forms an X+ ion. Do X and X+ have the same chemical properties? Explain.", "No. X+ has one fewer electron than X, so they have different chemical properties."],
        10154: ["Atom X has a mass number of 27 and forms a cation with a +3 charge. If the cation has 14 neutrons, how many electrons does it have?", "10 electrons."],
        10155: ["Which subatomic particles are present in a hydrogen ion?", "A proton only."],
        10156: ["Element X has atomic number 30 and electron arrangement 2,8,18,x. Find x.", "2."],
        10157: ["Element X has atomic number 25 and electron arrangement 2,8,13,x. Find x.", "2."],
        10158: ["A student says that any solid that conducts electricity must be a metal. Comment on this statement. (1 mark)", "The statement is incorrect because solid graphite also conducts electricity using delocalised electrons."],
        10159: ["Sodium is added to water and a piece of pH paper is then dipped into the solution. What is observed? Explain. (2 marks)", "The pH paper turns blue. Sodium reacts with water to produce sodium hydroxide, and the alkaline solution turns the pH paper blue."],
        10160: ["State one similarity between the atomic structures of lithium and fluorine atoms. (1 mark)", "They have the same number of occupied electron shells: two."],
        10161: ["X and Y are elements with electron arrangements 2,8,8 and 2,8,18,8 respectively. Are X and Y reactive? Explain. (2 marks)", "No. They have stable octet electron arrangements."],
        10162: ["At is located below iodine in the periodic table. Predict and explain the reactivity of At compared with iodine. (2 marks)", "At is less reactive than iodine because the reactivity of Group VII elements decreases down the group."],
        10163: ["What type of bonding holds the sodium ions and carbonate ions together in sodium carbonate? (1 mark)", "Ionic bonding."],
        10164: ["Element X has three isotopes. Using the relative abundances shown in the mass spectrum (22%, 23% and 55%), calculate the relative atomic mass of X.", "206 × 22% + 207 × 23% + 208 × 55% = 207.33."]
    };

    if (!Array.isArray(window.DOCX_FLASHCARDS)) return;
    window.DOCX_FLASHCARDS.forEach(card => {
        const translation = english[card.id];
        if (!translation) return;
        card.q_en = translation[0];
        card.a_en = translation[1];
    });
})();
